name: RSGDocking
channels:
  - conda-forge
  - schrodinger
dependencies:
  - python=3.11
  - pymol-bundle
  - meeko
  - fpocket
  - seaborn
  - numpy
  - scipy
  - rdkit
  - gemmi
  - vina
  - pip
  - molscrub
  - multiprocess
  - chemicalite
  - plip
  - pip:
      - ringtail
      - git+https://github.com/prody/ProDy.git@main#egg=prody
